sudo: required
services:
  - docker

before_install:
  - docker build -t pgupta04/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true pgupta04/docker-react npm run test -- --coverage

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-west-2-410377221518"
  bucket_path: "docker-react"
  on:
    branch: master 
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY